---
title: !r params$report_title
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
params:
  report_title: "B-cell repertoire analysis template"
  report_author: "Anonymus"
  tagged_repertoire: "../test_data/merged_repertoire.csv"
  sample_metadata: "../test_data/samples_meta.csv"
  condition_column: "Label"
---

## Setup

### Initialize tools

```{r}
# Import packages

library(tidyr)
library(purrr)
library(ggplot2)
library(ggsci)
library(plotly)
library(pheatmap)
library(DT)
library(immunarch)
```

```{r}
# Define function to show a nice table with download option

ALLOW_INTERACTION <- knitr::is_html_output()

show_tab <- function(tab, interaction=ALLOW_INTERACTION){
  if (interaction) {
    datatable(
      tab, extensions = "Buttons",
      options = list(
        scrollX="400px",
        dom = "Bfrtip",
        buttons = list(
          list(
            extend = "collection",
            buttons = c("csv", "excel"),
            text = "Download"
          )
        )
      )
    )
  } else {
    tab
  }
}

show_fig <- function(p, interaction=ALLOW_INTERACTION) {
  if (interaction) {
    ggplotly(p)
  } else {
    p
  }
}

color_names <- pal_npg()(9)
```


### Parse and preprocess data

```{r}
# Rearrange repertoire table to match Immunarch expectations

repertoire_folder <- "reconstructed_bcrs"
if (!dir.exists(repertoire_folder)) dir.create(repertoire_folder)

params$tagged_repertoire %>%
  read.csv(stringsAsFactors = FALSE) %>%
  group_split(Sample_code) %>%
  walk(function(x) {
    fn <- x$Sample_code %>%
      unique() %>%
      file.path(repertoire_folder, .)
    write.table(
      select(x, -Sample_code), paste(fn, "txt", sep="."),
      sep="\t", row.names=FALSE, quote = FALSE
    )
  })
```

```{r}
# Parse files with Immunarch

immdata <- repLoad(repertoire_folder)
unlink(repertoire_folder, recursive=TRUE, force=TRUE)
```

```{r}
# Add metadata

raw_metadata <- read.csv(params$sample_metadata)
raw_metadata$Condition <- raw_metadata[[params$condition_column]]
immdata$meta <- left_join(immdata$meta, raw_metadata, by=c(Sample="SampleID"))
N_CONDITION <- length(unique(raw_metadata$Condition))
```

```{r}
# Create long table for tidy operations

clonotype_freq_tab <- immdata$data %>%
  imap(~mutate(.x, Sample = .y)) %>%
  bind_rows() %>%
  left_join(immdata$meta, by="Sample") %>%
  mutate(
    logFreq = log(Proportion),
    receptorChain = substr(V.name, 1, 3)
  )
```

## Clonotype frequencies

### Clones recovered

```{r message=FALSE, warning=FALSE}
exp_vol <- repExplore(immdata$data, .method = "volume")
vis(exp_vol, .by = c("Condition"), .meta = immdata$meta)
```

```{r}
clonotype_summary <- clonotype_freq_tab %>%
  group_by(Sample, Condition, receptorChain) %>%
  summarise(
    Proportion_in_Sample = sum(Proportion),
    Mean_estimated_size  = mean(Proportion),
    Number_of_Clonotypes = n()
  )

show_tab(clonotype_summary)
```

```{r}
p <- clonotype_summary %>%
  ggplot(aes(x=Sample, y=Proportion_in_Sample, fill=receptorChain)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_npg() +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle=30, vjust=0.5, hjust=1)
    ) +
    labs(title="Proportion of Ig chains in samples", x="", y="Proportion")

show_fig(p)
```

```{r}
p <- clonotype_summary %>%
  ggplot(aes(x=Sample, y=Number_of_clonotypes, fill=receptorChain)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_npg() +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle=30, vjust=0.5, hjust=1)
    ) +
    labs(title="Number of individual clonotypes", x="", y="Clonotype")

show_fig(p)
```

### Spectratypes

```{r}
exp_len <- repExplore(immdata$data, .method = "len", .col = "aa")
vis(exp_len, .by = "Condition", .meta = immdata$meta) +
  scale_fill_npg()
```


### Distribution of proportions

```{r}
exp_cnt <- repExplore(immdata$data, .method = "count")
vis(exp_cnt) +
  scale_color_npg()
```


```{r}
display_clonotype_proportion_distribution <- function(in_tab, plot_title, chain_name=NULL, n_conditions=N_CONDITION) {
  p <- in_tab %>%
    filter(if(is.null(chain_name)) TRUE else receptorChain == !!chain_name) %>%
    ggplot(aes(x=Proportion)) +
      geom_density(aes(color=Condition)) +
      scale_x_log10() +
      scale_color_manual(values=rev(color_names[1:n_conditions])) +
      theme_bw() +
      labs(title=plot_title, x="Proportion", y="Density")
  
  show_fig(p)
}

display_clonotype_proportion_distribution(
  clonotype_freq_tab, "Distribution of clonotype proportions"
)
```

```{r}
display_clonotype_proportion_distribution(
  clonotype_freq_tab, "Distribution of IgH clonotype proportions", "IGH"
)
```

```{r}
display_clonotype_proportion_distribution(
  clonotype_freq_tab, "Distribution of IgK clonotype proportions", "IGK"
)
```

```{r}
display_clonotype_proportion_distribution(
  clonotype_freq_tab, "Distribution of IgL clonotype proportions", "IGL"
)
```

### Most abundant clones

```{r message=FALSE, warning=FALSE}
find_top_abundant_clones <- function(in_tab, chain_name=NULL) {
  in_tab %>%
    filter(if(is.null(chain_name)) TRUE else receptorChain == !!chain_name) %>%
    group_by(Condition, CDR3.nt) %>%
    mutate(Proportion = mean(Proportion)) %>%
    ungroup() %>%
    arrange(desc(Proportion)) %>%
    group_by(Condition) %>%
    group_split() %>%
    map(head, 30) %>%
    bind_rows() %>%
    distinct(CDR3.aa, CDR3.nt)
}

show_top_clone_proportions <- function(in_tab, top_clones, plot_title, chain_name=NULL) {
  in_tab %>%
    filter(if(is.null(chain_name)) TRUE else receptorChain == !!chain_name) %>%
    filter(CDR3.nt %in% top_clones$CDR3.nt) %>%
    select(Proportion, CDR3.aa, Condition) %>%
    mutate(
      CDR3.aa = factor(CDR3.aa, levels=unique(top_clones$CDR3.aa))
    ) %>%
    plot_ly(
      x = ~CDR3.aa, y = ~Proportion, color = ~Condition, type = "box",
      boxpoints = FALSE, width=1200, height=800,
      colors=rev(color_names[1:N_CONDITION])
    ) %>%
    layout(
      xaxis = list(title="", tickangle = 30, tickfont=list(size=12)),
      yaxis = list(title="Proportion", tickfont=list(size=12)),
      boxmode = "group",
      legend = list(orientation="h", xanchor="center", x=0.5),
      title = plot_title
    )
}

display_top_abundant_clonotypes <- function(in_tab, title, chain_name=NULL) {
  top_clones <- find_top_abundant_clones(in_tab, chain_name)
  show_top_clone_proportions(in_tab, top_clones, title, chain_name)
}

display_top_abundant_clonotypes(clonotype_freq_tab, "Top overall clonotypes")
```

```{r message=FALSE, warning=FALSE}
display_top_abundant_clonotypes(clonotype_freq_tab, "Top IgH clonotypes", "IGH")
```

```{r message=FALSE, warning=FALSE}
display_top_abundant_clonotypes(clonotype_freq_tab, "Top IgK clonotypes", "IGK")
```

```{r message=FALSE, warning=FALSE}
display_top_abundant_clonotypes(clonotype_freq_tab, "Top IgL clonotypes", "IGL")
```

## Differential abundance of clonotypes

### Top clones

```{r}
wrap_wilcox_stats <- function(data, condition_1, condition_2, condition_col="Condition", valuecol="Proportion") {
  skip_to_next <- FALSE
  data[[condition_col]] = as.character(data[[condition_col]] )
  x_vec = unlist(data[data[[condition_col]] == condition_1, valuecol])
  y_vec = unlist(data[data[[condition_col]] == condition_2, valuecol])
  tryCatch(wilcox.test(x_vec, y_vec), error = function(e) { skip_to_next <<- TRUE })
  if(skip_to_next) {
    stat <- list(p.value=1)
  } else {
    stat <- wilcox.test(x_vec, y_vec)
  }
    data.frame(
      Comparison = paste(condition_2, "vs.", condition_1, sep=" "),
      CDR3.aa = unique(data$CDR3.aa),
      Median_1 = median(y_vec, na.rm=TRUE),
      Median_2 = median(x_vec, na.rm=TRUE),
      FC = median(y_vec, na.rm=TRUE) / median(x_vec, na.rm=TRUE),
      p.value = stat$p.value,
      stringsAsFactors = FALSE
    )
}

find_top_differential_clonotypes <- function(in_tab) {
  
  compared_conditions <- raw_metadata$Condition %>%
    unique() %>%
    gtools::combinations(N_CONDITION, 2, .) %>%
    data.frame() %>%
    setNames(c("condition_1", "condition_2"))
  
  proportion_tab <- in_tab %>%
    group_by(Sample, CDR3.aa) %>%
    mutate(Proportion = sum(Proportion)) %>%
    distinct(Sample, Condition, CDR3.aa, Proportion) %>%
    group_by(CDR3.aa) %>%
    group_split() %>%
    map(function(x) {
      compared_conditions %>%
        pmap(function(y, condition_1, condition_2){
          wrap_wilcox_stats(x, condition_1, condition_2)
        }) %>%
        bind_rows()
    }) %>%
    bind_rows()
  
  proportion_tab
    
}

differential_clono_tab <- find_top_differential_clonotypes(clonotype_freq_tab)

differential_clono_tab %>%
  filter(!is.na(FC)) %>%
  arrange(p.value) %>%
  show_tab()
```

### Overview of statistics

```{r}
p <- differential_clono_tab %>%
  filter(!is.na(FC)) %>%
  mutate(
    Sign = ifelse(p.value < 0.05 & (FC > 2 | FC < 0.5), "Promising", "Noise"),
    Sign = factor(Sign, levels=c("Promising", "Noise"))
  ) %>%
  ggplot(aes(x=log2(FC), y=-log10(p.value), color=Sign, label=CDR3.aa)) +
  geom_point() +
  facet_grid(Comparison ~ .) +
  scale_color_npg() +
  theme_bw() +
  labs(
    title="Volcano plot of clonotype differences",
    x="log2(FoldChange)", y="-log10(p)", color=""
  )

show_fig(p)
```

### Most significant differences 

```{r message=FALSE, warning=FALSE}
top_clones <- differential_clono_tab %>%
  filter(!is.na(FC)) %>%
  group_by(Comparison) %>%
  group_split() %>%
  map(~arrange(.x, p.value, FC)) %>%
  map(head, 15) %>%
  bind_rows() %>%
  left_join(select(clonotype_freq_tab, CDR3.nt, CDR3.aa), by="CDR3.aa") %>%
  distinct(CDR3.nt, CDR3.aa)

show_top_clone_proportions(
  clonotype_freq_tab, top_clones,
  "Clonotypes differentailly present in conditions"
)
```

## Repertoire overlap

```{r}
imm_overlap_pb <- repOverlap(immdata$data, .method = "public", .verbose = F)
vis(imm_overlap_pb)
```


```{r}
imm_overlap_mrs <- repOverlap(immdata$data, .method = "morisita", .verbose = F)
vis(imm_overlap_mrs)
```

```{r}
imm_overlap_mrs %>%
  repOverlapAnalysis("mds") %>%
  vis()
```

## Repertoire diversities

```{r}

```

## Gene V usage

```{r}

```

## Clone lineages

```{r}

```
